import { Artisan, Category } from "./browse-by-categories-types";

export const categoriesData: Category[] = [
  {
    id: "plumber",
    name: "Plumber",
    icon: "plumber",
    color: "#3B82F6",
    description: "Professional plumbing services",
    count: 45,
  },
  {
    id: "barber",
    name: "Barber",
    icon: "barber",
    color: "#8B5CF6",
    description: "Expert hair cutting and styling",
    count: 32,
  },
  {
    id: "painter",
    name: "Painter",
    icon: "painter",
    color: "#F97316",
    description: "Interior and exterior painting",
    count: 28,
  },
  {
    id: "carpenter",
    name: "Carpenter",
    icon: "carpenter",
    color: "#10B981",
    description: "Custom woodwork and furniture",
    count: 38,
  },
  {
    id: "mechanic",
    name: "Mechanic",
    icon: "mechanic",
    color: "#EF4444",
    description: "Auto repair and maintenance",
    count: 52,
  },
  {
    id: "tech_repair",
    name: "Tech Repair",
    icon: "tech_repair",
    color: "#3B82F6",
    description: "Electronics and device repair",
    count: 24,
  },
  {
    id: "electrician",
    name: "Electrician",
    icon: "electrician",
    color: "#EAB308",
    description: "Electrical installation and repair",
    count: 41,
  },
  {
    id: "cleaner",
    name: "Cleaner",
    icon: "cleaner",
    color: "#3B82F6",
    description: "Professional cleaning services",
    count: 67,
  },
  {
    id: "photographer",
    name: "Photographer",
    icon: "photographer",
    color: "#6B7280",
    description: "Event and portrait photography",
    count: 19,
  },
  {
    id: "musician",
    name: "Musician",
    icon: "musician",
    color: "#8B5CF6",
    description: "Live music and entertainment",
    count: 15,
  },
  {
    id: "tailor",
    name: "Tailor",
    icon: "tailor",
    color: "#4F46E5",
    description: "Custom clothing and alterations",
    count: 22,
  },
  {
    id: "chef",
    name: "Chef",
    icon: "chef",
    color: "#EA580C",
    description: "Private cooking and catering",
    count: 18,
  },
];

export const artisansData: Artisan[] = [
  {
    id: "1",
    name: "John Doe",
    category: "plumber",
    location: "Ikeja, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.8,
    reviews: 127,
    specialties: ["Emergency repairs", "Pipe installation", "Drain cleaning"],
  },
  {
    id: "2",
    name: "Jane Smith",
    category: "plumber",
    location: "Abuja",
    image: "/worker.png",
    verified: true,
    rating: 4.9,
    reviews: 89,
    specialties: [
      "Bathroom renovation",
      "Water heater repair",
      "Leak detection",
    ],
  },
  {
    id: "3",
    name: "Michael Johnson",
    category: "plumber",
    location: "Accra",
    image: "/worker.png",
    verified: true,
    rating: 4.7,
    reviews: 156,
    specialties: [
      "Commercial plumbing",
      "Pipe replacement",
      "Fixture installation",
    ],
  },
  {
    id: "4",
    name: "Sarah Wilson",
    category: "plumber",
    location: "Victoria Island, Lagos",
    image: "/worker.png",
    verified: false,
    rating: 4.6,
    reviews: 73,
    specialties: ["Residential plumbing", "Emergency services", "Maintenance"],
  },
  {
    id: "5",
    name: "David Brown",
    category: "plumber",
    location: "Lekki, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.9,
    reviews: 201,
    specialties: [
      "Luxury installations",
      "Smart home plumbing",
      "Green solutions",
    ],
  },
  {
    id: "6",
    name: "Emily Davis",
    category: "plumber",
    location: "Ikoyi, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.8,
    reviews: 94,
    specialties: ["Kitchen plumbing", "Bathroom design", "Water filtration"],
  },

  // Barbers
  {
    id: "7",
    name: "Marcus Thompson",
    category: "barber",
    location: "Surulere, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.9,
    reviews: 312,
    specialties: ["Fade cuts", "Beard styling", "Traditional shaves"],
  },
  {
    id: "8",
    name: "Kevin Williams",
    category: "barber",
    location: "Yaba, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.7,
    reviews: 189,
    specialties: ["Modern cuts", "Hair design", "Grooming"],
  },

  // Painters
  {
    id: "9",
    name: "Robert Miller",
    category: "painter",
    location: "Gbagada, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.8,
    reviews: 145,
    specialties: [
      "Interior painting",
      "Exterior painting",
      "Decorative finishes",
    ],
  },
  {
    id: "10",
    name: "Lisa Anderson",
    category: "painter",
    location: "Magodo, Lagos",
    image: "/worker.png",
    verified: false,
    rating: 4.6,
    reviews: 67,
    specialties: [
      "Residential painting",
      "Color consultation",
      "Wall textures",
    ],
  },

  // Carpenters
  {
    id: "11",
    name: "James Wilson",
    category: "carpenter",
    location: "Ojodu, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.9,
    reviews: 178,
    specialties: ["Custom furniture", "Kitchen cabinets", "Built-in storage"],
  },
  {
    id: "12",
    name: "Thomas Garcia",
    category: "carpenter",
    location: "Ketu, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.7,
    reviews: 123,
    specialties: ["Wooden flooring", "Doors and windows", "Furniture repair"],
  },

  // Mechanics
  {
    id: "13",
    name: "Carlos Rodriguez",
    category: "mechanic",
    location: "Ikeja, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.8,
    reviews: 234,
    specialties: ["Engine repair", "Brake service", "Oil changes"],
  },
  {
    id: "14",
    name: "Antonio Martinez",
    category: "mechanic",
    location: "Alaba, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.9,
    reviews: 167,
    specialties: ["Transmission repair", "AC service", "Diagnostics"],
  },

  // Tech Repair
  {
    id: "15",
    name: "Alex Chen",
    category: "tech_repair",
    location: "Computer Village, Lagos",
    image: "/worker.png",
    verified: true,
    rating: 4.9,
    reviews: 298,
    specialties: ["Phone repair", "Laptop service", "Data recovery"],
  },
  {
    id: "16",
    name: "Daniel Kim",
    category: "tech_repair",
    location: "Victoria Island, Lagos",
    image: "/worker.png",
    verified: false,
    rating: 4.6,
    reviews: 89,
    specialties: ["Gaming consoles", "Smart devices", "Software issues"],
  },
];
